name: weather_app
description: "A simple weather app."

version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  http: ^1.2.1
  smooth_page_indicator:
  geolocator: ^12.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0
  network_image_mock: ^2.1.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/weather_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/weather_logo.png"
  adaptive_icon_background: "assets/weather_logo.png"
  adaptive_icon_foreground: "assets/weather_logo.png"

flutter_native_splash:
  android: true
  ios: true
  image: assets/weather_logo.png
  color: "#141414"